name: 📦 00_build-rootfs-lite
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ⏬ 下载 ImageBuilder
        run: |
          curl -L -o imagebuilder.tar.zst https://github.com/Kwonelee/fenliu/releases/download/rootfs/istoreos-imagebuilder-24.10.2-armsr-armv8.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xvf imagebuilder.tar.zst
          mv istoreos-imagebuilder-* imagebuilder

      - name: ⚙️ 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zstd curl unzip tree

      - name: 🧱 构建iStoreOS-rootfs
        run: |
          #cd imagebuilder
          #echo "启用rootfs.tar.gz配置"
          #sed -i 's/# CONFIG_TARGET_ROOTFS_TARGZ is not set/CONFIG_TARGET_ROOTFS_TARGZ=y/' .config
          cd imagebuilder
          make image PROFILE=generic PACKAGES="-libustream-mbedtls" FILES="files"

      - name: 🚀 上传到 Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: iStoreOS-24.10.2-arm64-rootfs-lite
          files: |
            imagebuilder/bin/targets/armsr/armv8/*generic-rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
